// AUTO-GENERATED from Immolate (SpectralPack/Immolate) items.cl + debug.cl
// Do not hand-edit; regenerate from source if the game updates.
package analyzer

data class Item(val id: String, val displayName: String) {
    override fun toString() = displayName
}

object Pools {
    val COMMON_JOKERS = listOf(
        Item("Joker", "Joker"),
        Item("Greedy_Joker", "Greedy Joker"),
        Item("Lusty_Joker", "Lusty Joker"),
        Item("Wrathful_Joker", "Wrathful Joker"),
        Item("Gluttonous_Joker", "Gluttonous Joker"),
        Item("Jolly_Joker", "Jolly Joker"),
        Item("Zany_Joker", "Zany Joker"),
        Item("Mad_Joker", "Mad Joker"),
        Item("Crazy_Joker", "Crazy Joker"),
        Item("Droll_Joker", "Droll Joker"),
        Item("Sly_Joker", "Sly Joker"),
        Item("Wily_Joker", "Wily Joker"),
        Item("Clever_Joker", "Clever Joker"),
        Item("Devious_Joker", "Devious Joker"),
        Item("Crafty_Joker", "Crafty Joker"),
        Item("Half_Joker", "Half Joker"),
        Item("Credit_Card", "Credit Card"),
        Item("Banner", "Banner"),
        Item("Mystic_Summit", "Mystic Summit"),
        Item("_8_Ball", "8 Ball"),
        Item("Misprint", "Misprint"),
        Item("Raised_Fist", "Raised Fist"),
        Item("Chaos_the_Clown", "Chaos the Clown"),
        Item("Scary_Face", "Scary Face"),
        Item("Abstract_Joker", "Abstract Joker"),
        Item("Delayed_Gratification", "Delayed Gratification"),
        Item("Gros_Michel", "Gros Michel"),
        Item("Even_Steven", "Even Steven"),
        Item("Odd_Todd", "Odd Todd"),
        Item("Scholar", "Scholar"),
        Item("Business_Card", "Business Card"),
        Item("Supernova", "Supernova"),
        Item("Ride_the_Bus", "Ride the Bus"),
        Item("Egg", "Egg"),
        Item("Runner", "Runner"),
        Item("Ice_Cream", "Ice Cream"),
        Item("Splash", "Splash"),
        Item("Blue_Joker", "Blue Joker"),
        Item("Faceless_Joker", "Faceless Joker"),
        Item("Green_Joker", "Green Joker"),
        Item("Superposition", "Superposition"),
        Item("To_Do_List", "To Do List"),
        Item("Cavendish", "Cavendish"),
        Item("Red_Card", "Red Card"),
        Item("Square_Joker", "Square Joker"),
        Item("Riff_raff", "Riff-raff"),
        Item("Photograph", "Photograph"),
        Item("Reserved_Parking", "Reserved Parking"),
        Item("Mail_In_Rebate", "Mail-In Rebate"),
        Item("Hallucination", "Hallucination"),
        Item("Fortune_Teller", "Fortune Teller"),
        Item("Juggler", "Juggler"),
        Item("Drunkard", "Drunkard"),
        Item("Golden_Joker", "Golden Joker"),
        Item("Popcorn", "Popcorn"),
        Item("Walkie_Talkie", "Walkie Talkie"),
        Item("Smiley_Face", "Smiley Face"),
        Item("Golden_Ticket", "Golden Ticket"),
        Item("Swashbuckler", "Swashbuckler"),
        Item("Hanging_Chad", "Hanging Chad"),
        Item("Shoot_the_Moon", "Shoot the Moon")
    )
    val UNCOMMON_JOKERS = listOf(
        Item("Joker_Stencil", "Joker Stencil"),
        Item("Four_Fingers", "Four Fingers"),
        Item("Mime", "Mime"),
        Item("Ceremonial_Dagger", "Ceremonial Dagger"),
        Item("Marble_Joker", "Marble Joker"),
        Item("Loyalty_Card", "Loyalty Card"),
        Item("Dusk", "Dusk"),
        Item("Fibonacci", "Fibonacci"),
        Item("Steel_Joker", "Steel Joker"),
        Item("Hack", "Hack"),
        Item("Pareidolia", "Pareidolia"),
        Item("Space_Joker", "Space Joker"),
        Item("Burglar", "Burglar"),
        Item("Blackboard", "Blackboard"),
        Item("Sixth_Sense", "Sixth Sense"),
        Item("Constellation", "Constellation"),
        Item("Hiker", "Hiker"),
        Item("Card_Sharp", "Card Sharp"),
        Item("Madness", "Madness"),
        Item("Seance", "Seance"),
        Item("Vampire", "Vampire"),
        Item("Shortcut", "Shortcut"),
        Item("Hologram", "Hologram"),
        Item("Cloud_9", "Cloud 9"),
        Item("Rocket", "Rocket"),
        Item("Midas_Mask", "Midas Mask"),
        Item("Luchador", "Luchador"),
        Item("Gift_Card", "Gift Card"),
        Item("Turtle_Bean", "Turtle Bean"),
        Item("Erosion", "Erosion"),
        Item("To_the_Moon", "To the Moon"),
        Item("Stone_Joker", "Stone Joker"),
        Item("Lucky_Cat", "Lucky Cat"),
        Item("Bull", "Bull"),
        Item("Diet_Cola", "Diet Cola"),
        Item("Trading_Card", "Trading Card"),
        Item("Flash_Card", "Flash Card"),
        Item("Spare_Trousers", "Spare Trousers"),
        Item("Ramen", "Ramen"),
        Item("Seltzer", "Seltzer"),
        Item("Castle", "Castle"),
        Item("Mr_Bones", "Mr. Bones"),
        Item("Acrobat", "Acrobat"),
        Item("Sock_and_Buskin", "Sock and Buskin"),
        Item("Troubadour", "Troubadour"),
        Item("Certificate", "Certificate"),
        Item("Smeared_Joker", "Smeared Joker"),
        Item("Throwback", "Throwback"),
        Item("Rough_Gem", "Rough Gem"),
        Item("Bloodstone", "Bloodstone"),
        Item("Arrowhead", "Arrowhead"),
        Item("Onyx_Agate", "Onyx Agate"),
        Item("Glass_Joker", "Glass Joker"),
        Item("Showman", "Showman"),
        Item("Flower_Pot", "Flower Pot"),
        Item("Merry_Andy", "Merry Andy"),
        Item("Oops_All_6s", "Oops! All 6s"),
        Item("The_Idol", "The Idol"),
        Item("Seeing_Double", "Seeing Double"),
        Item("Matador", "Matador"),
        Item("Satellite", "Satellite"),
        Item("Cartomancer", "Cartomancer"),
        Item("Astronomer", "Astronomer"),
        Item("Bootstraps", "Bootstraps")
    )
    val RARE_JOKERS = listOf(
        Item("DNA", "DNA"),
        Item("Vagabond", "Vagabond"),
        Item("Baron", "Baron"),
        Item("Obelisk", "Obelisk"),
        Item("Baseball_Card", "Baseball Card"),
        Item("Ancient_Joker", "Ancient Joker"),
        Item("Campfire", "Campfire"),
        Item("Blueprint", "Blueprint"),
        Item("Wee_Joker", "Wee Joker"),
        Item("Hit_the_Road", "Hit the Road"),
        Item("The_Duo", "The Duo"),
        Item("The_Trio", "The Trio"),
        Item("The_Family", "The Family"),
        Item("The_Order", "The Order"),
        Item("The_Tribe", "The Tribe"),
        Item("Stuntman", "Stuntman"),
        Item("Invisible_Joker", "Invisible Joker"),
        Item("Brainstorm", "Brainstorm"),
        Item("Drivers_License", "Driver\'s License"),
        Item("Burnt_Joker", "Burnt Joker")
    )
    val LEGENDARY_JOKERS = listOf(
        Item("Canio", "Canio"),
        Item("Triboulet", "Triboulet"),
        Item("Yorick", "Yorick"),
        Item("Chicot", "Chicot"),
        Item("Perkeo", "Perkeo")
    )
    val TAROTS = listOf(
        Item("The_Fool", "The Fool"),
        Item("The_Magician", "The Magician"),
        Item("The_High_Priestess", "The High Priestess"),
        Item("The_Empress", "The Empress"),
        Item("The_Emperor", "The Emperor"),
        Item("The_Hierophant", "The Hierophant"),
        Item("The_Lovers", "The Lovers"),
        Item("The_Chariot", "The Chariot"),
        Item("Justice", "Justice"),
        Item("The_Hermit", "The Hermit"),
        Item("The_Wheel_of_Fortune", "The Wheel of Fortune"),
        Item("Strength", "Strength"),
        Item("The_Hanged_Man", "The Hanged Man"),
        Item("Death", "Death"),
        Item("Temperance", "Temperance"),
        Item("The_Devil", "The Devil"),
        Item("The_Tower", "The Tower"),
        Item("The_Star", "The Star"),
        Item("The_Moon", "The Moon"),
        Item("The_Sun", "The Sun"),
        Item("Judgement", "Judgement"),
        Item("The_World", "The World")
    )
    val PLANETS = listOf(
        Item("Mercury", "Mercury"),
        Item("Venus", "Venus"),
        Item("Earth", "Earth"),
        Item("Mars", "Mars"),
        Item("Jupiter", "Jupiter"),
        Item("Saturn", "Saturn"),
        Item("Uranus", "Uranus"),
        Item("Neptune", "Neptune"),
        Item("Pluto", "Pluto"),
        Item("Planet_X", "Planet X"),
        Item("Ceres", "Ceres"),
        Item("Eris", "Eris")
    )
    val SPECTRALS = listOf(
        Item("Familiar", "Familiar"),
        Item("Grim", "Grim"),
        Item("Incantation", "Incantation"),
        Item("Talisman", "Talisman"),
        Item("Aura", "Aura"),
        Item("Wraith", "Wraith"),
        Item("Sigil", "Sigil"),
        Item("Ouija", "Ouija"),
        Item("Ectoplasm", "Ectoplasm"),
        Item("Immolate", "Immolate"),
        Item("Ankh", "Ankh"),
        Item("Deja_Vu", "Deja Vu"),
        Item("Hex", "Hex"),
        Item("Trance", "Trance"),
        Item("Medium", "Medium"),
        Item("Cryptid", "Cryptid"),
        Item("RETRY", "RETRY"),
        Item("RETRY", "RETRY")
    )
    val VOUCHERS = listOf(
        Item("Overstock", "Overstock"),
        Item("Overstock_Plus", "Overstock Plus"),
        Item("Clearance_Sale", "Clearance Sale"),
        Item("Liquidation", "Liquidation"),
        Item("Hone", "Hone"),
        Item("Glow_Up", "Glow Up"),
        Item("Reroll_Surplus", "Reroll Surplus"),
        Item("Reroll_Glut", "Reroll Glut"),
        Item("Crystal_Ball", "Crystal Ball"),
        Item("Omen_Globe", "Omen Globe"),
        Item("Telescope", "Telescope"),
        Item("Observatory", "Observatory"),
        Item("Grabber", "Grabber"),
        Item("Nacho_Tong", "Nacho Tong"),
        Item("Wasteful", "Wasteful"),
        Item("Recyclomancy", "Recyclomancy"),
        Item("Tarot_Merchant", "Tarot Merchant"),
        Item("Tarot_Tycoon", "Tarot Tycoon"),
        Item("Planet_Merchant", "Planet Merchant"),
        Item("Planet_Tycoon", "Planet Tycoon"),
        Item("Seed_Money", "Seed Money"),
        Item("Money_Tree", "Money Tree"),
        Item("Blank", "Blank"),
        Item("Antimatter", "Antimatter"),
        Item("Magic_Trick", "Magic Trick"),
        Item("Illusion", "Illusion"),
        Item("Hieroglyph", "Hieroglyph"),
        Item("Petroglyph", "Petroglyph"),
        Item("Directors_Cut", "Director\'s Cut"),
        Item("Retcon", "Retcon"),
        Item("Paint_Brush", "Paint Brush"),
        Item("Palette", "Palette")
    )
    val TAGS = listOf(
        Item("Uncommon_Tag", "Uncommon Tag"),
        Item("Rare_Tag", "Rare Tag"),
        Item("Negative_Tag", "Negative Tag"),
        Item("Foil_Tag", "Foil Tag"),
        Item("Holographic_Tag", "Holographic Tag"),
        Item("Polychrome_Tag", "Polychrome Tag"),
        Item("Investment_Tag", "Investment Tag"),
        Item("Voucher_Tag", "Voucher Tag"),
        Item("Boss_Tag", "Boss Tag"),
        Item("Standard_Tag", "Standard Tag"),
        Item("Charm_Tag", "Charm Tag"),
        Item("Meteor_Tag", "Meteor Tag"),
        Item("Buffoon_Tag", "Buffoon Tag"),
        Item("Handy_Tag", "Handy Tag"),
        Item("Garbage_Tag", "Garbage Tag"),
        Item("Ethereal_Tag", "Ethereal Tag"),
        Item("Coupon_Tag", "Coupon Tag"),
        Item("Double_Tag", "Double Tag"),
        Item("Juggle_Tag", "Juggle Tag"),
        Item("D6_Tag", "D6 Tag"),
        Item("Top_up_Tag", "Top-up Tag"),
        Item("Speed_Tag", "Speed Tag"),
        Item("Orbital_Tag", "Orbital Tag"),
        Item("Economy_Tag", "Economy Tag")
    )
    val BOSSES = listOf(
        Item("The_Arm", "The Arm"),
        Item("The_Club", "The Club"),
        Item("The_Eye", "The Eye"),
        Item("Amber_Acorn", "Amber Acorn"),
        Item("Cerulean_Bell", "Cerulean Bell"),
        Item("Crimson_Heart", "Crimson Heart"),
        Item("Verdant_Leaf", "Verdant Leaf"),
        Item("Violet_Vessel", "Violet Vessel"),
        Item("The_Fish", "The Fish"),
        Item("The_Flint", "The Flint"),
        Item("The_Goad", "The Goad"),
        Item("The_Head", "The Head"),
        Item("The_Hook", "The Hook"),
        Item("The_House", "The House"),
        Item("The_Manacle", "The Manacle"),
        Item("The_Mark", "The Mark"),
        Item("The_Mouth", "The Mouth"),
        Item("The_Needle", "The Needle"),
        Item("The_Ox", "The Ox"),
        Item("The_Pillar", "The Pillar"),
        Item("The_Plant", "The Plant"),
        Item("The_Psychic", "The Psychic"),
        Item("The_Serpent", "The Serpent"),
        Item("The_Tooth", "The Tooth"),
        Item("The_Wall", "The Wall"),
        Item("The_Water", "The Water"),
        Item("The_Wheel", "The Wheel"),
        Item("The_Window", "The Window")
    )
    val ENHANCEMENTS = listOf(
        Item("Bonus_Card", "Bonus"),
        Item("Mult_Card", "Mult"),
        Item("Wild_Card", "Wild"),
        Item("Glass_Card", "Glass"),
        Item("Steel_Card", "Steel"),
        Item("Stone_Card", "Stone"),
        Item("Gold_Card", "Gold"),
        Item("Lucky_Card", "Lucky")
    )
    val CARDS = listOf(
        Item("C_2", "2 of Clubs"),
        Item("C_3", "3 of Clubs"),
        Item("C_4", "4 of Clubs"),
        Item("C_5", "5 of Clubs"),
        Item("C_6", "6 of Clubs"),
        Item("C_7", "7 of Clubs"),
        Item("C_8", "8 of Clubs"),
        Item("C_9", "9 of Clubs"),
        Item("C_A", "Ace of Clubs"),
        Item("C_J", "Jack of Clubs"),
        Item("C_K", "King of Clubs"),
        Item("C_Q", "Queen of Clubs"),
        Item("C_T", "10 of Clubs"),
        Item("D_2", "2 of Diamonds"),
        Item("D_3", "3 of Diamonds"),
        Item("D_4", "4 of Diamonds"),
        Item("D_5", "5 of Diamonds"),
        Item("D_6", "6 of Diamonds"),
        Item("D_7", "7 of Diamonds"),
        Item("D_8", "8 of Diamonds"),
        Item("D_9", "9 of Diamonds"),
        Item("D_A", "Ace of Diamonds"),
        Item("D_J", "Jack of Diamonds"),
        Item("D_K", "King of Diamonds"),
        Item("D_Q", "Queen of Diamonds"),
        Item("D_T", "10 of Diamonds"),
        Item("H_2", "2 of Hearts"),
        Item("H_3", "3 of Hearts"),
        Item("H_4", "4 of Hearts"),
        Item("H_5", "5 of Hearts"),
        Item("H_6", "6 of Hearts"),
        Item("H_7", "7 of Hearts"),
        Item("H_8", "8 of Hearts"),
        Item("H_9", "9 of Hearts"),
        Item("H_A", "Ace of Hearts"),
        Item("H_J", "Jack of Hearts"),
        Item("H_K", "King of Hearts"),
        Item("H_Q", "Queen of Hearts"),
        Item("H_T", "10 of Hearts"),
        Item("S_2", "2 of Spades"),
        Item("S_3", "3 of Spades"),
        Item("S_4", "4 of Spades"),
        Item("S_5", "5 of Spades"),
        Item("S_6", "6 of Spades"),
        Item("S_7", "7 of Spades"),
        Item("S_8", "8 of Spades"),
        Item("S_9", "9 of Spades"),
        Item("S_A", "Ace of Spades"),
        Item("S_J", "Jack of Spades"),
        Item("S_K", "King of Spades"),
        Item("S_Q", "Queen of Spades"),
        Item("S_T", "10 of Spades")
    )

    val FINISHER_BOSSES = setOf("Amber_Acorn","Verdant_Leaf","Violet_Vessel","Crimson_Heart","Cerulean_Bell")
    val NORMAL_BOSSES = BOSSES.filter { it.id !in FINISHER_BOSSES }
    val FINISHER_BOSS_ITEMS = BOSSES.filter { it.id in FINISHER_BOSSES }

    // Bosses unavailable before a given ante (unconditional base-game rule, independent of profile unlocks)
    val BOSS_ANTE_GATE: Map<String, Int> = mapOf(
        "The_Mouth" to 2, "The_Fish" to 2, "The_Wall" to 2, "The_House" to 2, "The_Mark" to 2,
        "The_Wheel" to 2, "The_Arm" to 2, "The_Water" to 2, "The_Needle" to 2, "The_Flint" to 2,
        "The_Tooth" to 3, "The_Eye" to 3,
        "The_Plant" to 4,
        "The_Serpent" to 5,
        "The_Ox" to 6
    )
    // Tags unavailable in ante 1 (unconditional base-game rule)
    val TAG_ANTE_GATE: Set<String> = setOf(
        "Negative_Tag", "Standard_Tag", "Meteor_Tag", "Buffoon_Tag", "Handy_Tag",
        "Garbage_Tag", "Ethereal_Tag", "Top_up_Tag", "Orbital_Tag"
    )

    val EDITIONS = listOf(
        Item("No_Edition", "No Edition"),
        Item("Foil", "Foil"),
        Item("Holographic", "Holographic"),
        Item("Polychrome", "Polychrome"),
        Item("Negative", "Negative")
    )
    val SEALS = listOf(
        Item("No_Seal", "No Seal"),
        Item("Red_Seal", "Red Seal"),
        Item("Blue_Seal", "Blue Seal"),
        Item("Gold_Seal", "Gold Seal"),
        Item("Purple_Seal", "Purple Seal")
    )

    // Pack variants: (id, displayName, family, cardsShown, cardsPicked, weight)
    data class PackKind(val item: Item, val family: String, val size: Int, val choices: Int, val weight: Double)
    val PACK_KINDS = listOf(
        PackKind(Item("Arcana_Pack","Arcana Pack"), "Arcana", 3, 1, 4.0),
        PackKind(Item("Jumbo_Arcana_Pack","Jumbo Arcana Pack"), "Arcana", 5, 1, 2.0),
        PackKind(Item("Mega_Arcana_Pack","Mega Arcana Pack"), "Arcana", 5, 2, 0.5),
        PackKind(Item("Celestial_Pack","Celestial Pack"), "Celestial", 3, 1, 4.0),
        PackKind(Item("Jumbo_Celestial_Pack","Jumbo Celestial Pack"), "Celestial", 5, 1, 2.0),
        PackKind(Item("Mega_Celestial_Pack","Mega Celestial Pack"), "Celestial", 5, 2, 0.5),
        PackKind(Item("Standard_Pack","Standard Pack"), "Standard", 3, 1, 4.0),
        PackKind(Item("Jumbo_Standard_Pack","Jumbo Standard Pack"), "Standard", 5, 1, 2.0),
        PackKind(Item("Mega_Standard_Pack","Mega Standard Pack"), "Standard", 5, 2, 0.5),
        PackKind(Item("Buffoon_Pack","Buffoon Pack"), "Buffoon", 2, 1, 1.2),
        PackKind(Item("Jumbo_Buffoon_Pack","Jumbo Buffoon Pack"), "Buffoon", 4, 1, 0.6),
        PackKind(Item("Mega_Buffoon_Pack","Mega Buffoon Pack"), "Buffoon", 4, 2, 0.15),
        PackKind(Item("Spectral_Pack","Spectral Pack"), "Spectral", 2, 1, 0.6),
        PackKind(Item("Jumbo_Spectral_Pack","Jumbo Spectral Pack"), "Spectral", 4, 1, 0.3),
        PackKind(Item("Mega_Spectral_Pack","Mega Spectral Pack"), "Spectral", 4, 2, 0.07)
    )
    val PACK_TOTAL_WEIGHT = PACK_KINDS.sumOf { it.weight }

    val JOKERS = sequenceOf<Item>()
        .plus(COMMON_JOKERS)
        .plus(UNCOMMON_JOKERS)
        .plus(RARE_JOKERS)
        .plus(LEGENDARY_JOKERS)
}